version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    labels:
      - "dependencies"
    groups:
      babel:
        patterns:
          - "@babel/*"
    ignore:
      # Upgrade to v7 is non-trivial, including changing the Sass compiler required (see https://docs.fontawesome.com/upgrade/scss).
      # It's probably better to wait to handle this with the future upgrade of the base theme.
      - dependency-name: "@fortawesome/fontawesome-free"
        update-types: [ "version-update:semver-major" ]
      # Upgrade to v4 causes "Could not resolve "jquery/dist/jquery.min.js" error during site generation (but apparently
      # not when running the dev server?). Possibly something to do with jQuery migrating to ESM.
      # It's probably better to wait to handle this with the future upgrade of the base theme.
      - dependency-name: "jquery"
        update-types: [ "version-update:semver-major" ]
    schedule:
      interval: "weekly"
      day: "monday" # explicit, even though it's the weekly default
      time: "07:00" # UTC
