name: Build

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

defaults:
  run:
    shell: bash # Every steps will have a /usr/bin/bash --noprofile --norc -e -o pipefail

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout current project
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Setup Hugo
        uses: gatling/gatling.io-doc/.github/actions/setup-hugo@f3dac394181bf645bffa511e37b05dc843310f02 # main
        with:
          hugo-version: '0.161.1'

      - name: Build example site
        working-directory: exampleSite
        run: hugo --minify
